#
# Copyright (c) 1998-1999 Sigma6 Inc.  All rights reserved.
#
# $Id: Makefile,v 1.1 2000/06/20 15:44:12 lswanson Exp $
#

include ../../make.defs

PACKAGE = COM.worlddealer
PACKAGEDIR = $(LIBDIR)/COM/worlddealer
SOURCES = 
CLASSES = ${SOURCES:%.java=$(PACKAGEDIR)/%.class}
SUBDIRS = account cfx commerce content

include ../../make.rules
